### ISSUE TITLE
Incorrect links to organisations

### ISSUE THREAD

**Issue by EmilyBoarer** [camvote/bob-gui#7]
on pages like https://camvote.org/jcsu/22-23/jesident/ or similar, the link under "organisation" is broken: tries to take you to https://camvote.orghttps//jcsu.jesus.cam.ac.uk//

**Comment by lewis-wf** [comment]
This issue was moved to the bob-providers so we can apply a 'bodge' patch - changing the YAML code rather than the UI code itself (if we are planning to rewrite the backend anyway). https://github.com/camvote/bob-providers/issues/2

Closed.
